import type { card } from "@types"

export default [
  {
    id: "ace_of_clubs",
    value: "ace",
    suit: "clubs",
    img: "./cards/ace_of_clubs.webp",
  },
  {
    id: "ace_of_diamonds",
    value: "ace",
    suit: "diamonds",
    img: "./cards/ace_of_diamonds.webp",
  },
  {
    id: "ace_of_hearts",
    value: "ace",
    suit: "hearts",
    img: "./cards/ace_of_hearts.webp",
  },
  {
    id: "ace_of_spades",
    value: "ace",
    suit: "spades",
    img: "./cards/ace_of_spades.webp",
  },
  {
    id: "jack_of_clubs",
    value: "jack",
    suit: "clubs",
    img: "./cards/jack_of_clubs.webp",
  },
  {
    id: "jack_of_diamonds",
    value: "jack",
    suit: "diamonds",
    img: "./cards/jack_of_diamonds.webp",
  },
  {
    id: "jack_of_hearts",
    value: "jack",
    suit: "hearts",
    img: "./cards/jack_of_hearts.webp",
  },
  {
    id: "jack_of_spades",
    value: "jack",
    suit: "spades",
    img: "./cards/jack_of_spades.webp",
  },
  {
    id: "queen_of_clubs",
    value: "queen",
    suit: "clubs",
    img: "./cards/queen_of_clubs.webp",
  },
  {
    id: "queen_of_diamonds",
    value: "queen",
    suit: "diamonds",
    img: "./cards/queen_of_diamonds.webp",
  },
  {
    id: "queen_of_hearts",
    value: "queen",
    suit: "hearts",
    img: "./cards/queen_of_hearts.webp",
  },
  {
    id: "queen_of_spades",
    value: "queen",
    suit: "spades",
    img: "./cards/queen_of_spades.webp",
  },
  {
    id: "king_of_clubs",
    value: "king",
    suit: "clubs",
    img: "./cards/king_of_clubs.webp",
  },
  {
    id: "king_of_diamonds",
    value: "king",
    suit: "diamonds",
    img: "./cards/king_of_diamonds.webp",
  },
  {
    id: "king_of_hearts",
    value: "king",
    suit: "hearts",
    img: "./cards/king_of_hearts.webp",
  },
  {
    id: "king_of_spades",
    value: "king",
    suit: "spades",
    img: "./cards/king_of_spades.webp",
  },
  {
    id: "2_of_clubs",
    value: 2,
    suit: "clubs",
    img: "./cards/2_of_clubs.webp",
  },
  {
    id: "2_of_diamonds",
    value: 2,
    suit: "diamonds",
    img: "./cards/2_of_diamonds.webp",
  },
  {
    id: "2_of_hearts",
    value: 2,
    suit: "hearts",
    img: "./cards/2_of_hearts.webp",
  },
  {
    id: "2_of_spades",
    value: 2,
    suit: "spades",
    img: "./cards/2_of_spades.webp",
  },
  {
    id: "3_of_clubs",
    value: 3,
    suit: "clubs",
    img: "./cards/3_of_clubs.webp",
  },
  {
    id: "3_of_diamonds",
    value: 3,
    suit: "diamonds",
    img: "./cards/3_of_diamonds.webp",
  },
  {
    id: "3_of_hearts",
    value: 3,
    suit: "hearts",
    img: "./cards/3_of_hearts.webp",
  },
  {
    id: "3_of_spades",
    value: 3,
    suit: "spades",
    img: "./cards/3_of_spades.webp",
  },
  {
    id: "4_of_clubs",
    value: 4,
    suit: "clubs",
    img: "./cards/4_of_clubs.webp",
  },
  {
    id: "4_of_diamonds",
    value: 4,
    suit: "diamonds",
    img: "./cards/4_of_diamonds.webp",
  },
  {
    id: "4_of_hearts",
    value: 4,
    suit: "hearts",
    img: "./cards/4_of_hearts.webp",
  },
  {
    id: "4_of_spades",
    value: 4,
    suit: "spades",
    img: "./cards/4_of_spades.webp",
  },
  {
    id: "5_of_clubs",
    value: 5,
    suit: "clubs",
    img: "./cards/5_of_clubs.webp",
  },
  {
    id: "5_of_diamonds",
    value: 5,
    suit: "diamonds",
    img: "./cards/5_of_diamonds.webp",
  },
  {
    id: "5_of_hearts",
    value: 5,
    suit: "hearts",
    img: "./cards/5_of_hearts.webp",
  },
  {
    id: "5_of_spades",
    value: 5,
    suit: "spades",
    img: "./cards/5_of_spades.webp",
  },
  {
    id: "6_of_clubs",
    value: 6,
    suit: "clubs",
    img: "./cards/6_of_clubs.webp",
  },
  {
    id: "6_of_diamonds",
    value: 6,
    suit: "diamonds",
    img: "./cards/6_of_diamonds.webp",
  },
  {
    id: "6_of_hearts",
    value: 6,
    suit: "hearts",
    img: "./cards/6_of_hearts.webp",
  },
  {
    id: "6_of_spades",
    value: 6,
    suit: "spades",
    img: "./cards/6_of_spades.webp",
  },
  {
    id: "7_of_clubs",
    value: 7,
    suit: "clubs",
    img: "./cards/7_of_clubs.webp",
  },
  {
    id: "7_of_diamonds",
    value: 7,
    suit: "diamonds",
    img: "./cards/7_of_diamonds.webp",
  },
  {
    id: "7_of_hearts",
    value: 7,
    suit: "hearts",
    img: "./cards/7_of_hearts.webp",
  },
  {
    id: "7_of_spades",
    value: 7,
    suit: "spades",
    img: "./cards/7_of_spades.webp",
  },
  {
    id: "8_of_clubs",
    value: 8,
    suit: "clubs",
    img: "./cards/8_of_clubs.webp",
  },
  {
    id: "8_of_diamonds",
    value: 8,
    suit: "diamonds",
    img: "./cards/8_of_diamonds.webp",
  },
  {
    id: "8_of_hearts",
    value: 8,
    suit: "hearts",
    img: "./cards/8_of_hearts.webp",
  },
  {
    id: "8_of_spades",
    value: 8,
    suit: "spades",
    img: "./cards/8_of_spades.webp",
  },
  {
    id: "9_of_clubs",
    value: 9,
    suit: "clubs",
    img: "./cards/9_of_clubs.webp",
  },
  {
    id: "9_of_diamonds",
    value: 9,
    suit: "diamonds",
    img: "./cards/9_of_diamonds.webp",
  },
  {
    id: "9_of_hearts",
    value: 9,
    suit: "hearts",
    img: "./cards/9_of_hearts.webp",
  },
  {
    id: "9_of_spades",
    value: 9,
    suit: "spades",
    img: "./cards/9_of_spades.webp",
  },
  {
    id: "10_of_clubs",
    value: 10,
    suit: "clubs",
    img: "./cards/10_of_clubs.webp",
  },
  {
    id: "10_of_diamonds",
    value: 10,
    suit: "diamonds",
    img: "./cards/10_of_diamonds.webp",
  },
  {
    id: "10_of_hearts",
    value: 10,
    suit: "hearts",
    img: "./cards/10_of_hearts.webp",
  },
  {
    id: "10_of_spades",
    value: 10,
    suit: "spades",
    img: "./cards/10_of_spades.webp",
  },
] as card[]
